from __future__ import annotations

import duckdb
import pandas as pd
from pathlib import Path
from typing import Any, Callable, Dict, Iterator, List, Optional, Sequence, Tuple, Union

class HybridFrameError(Exception): ...

class Engine: ...

class HybridFrame:
    _pool: ...
    _POOL_MAX_SIZE: int
    _leased_connections: ...

    @classmethod
    def acquire_connection(cls) -> duckdb.DuckDBPyConnection: ...
    @classmethod
    def release_connection(cls, conn: duckdb.DuckDBPyConnection) -> None: ...
    @classmethod
    def close_all_connections(cls) -> None: ...

    def __init__(
        self,
        memory_limit: Optional[str] = ...,
        temp_directory: Optional[str] = ...,
        threads: Optional[int] = ...,
        connection: Optional[duckdb.DuckDBPyConnection] = ...,
    ) -> None: ...

    @classmethod
    def from_csv(cls, file_path: Union[str, Path], **csv_kwargs: Any) -> HybridFrame: ...
    @classmethod
    def from_parquet(cls, file_path: Union[str, Path], **pq_kwargs: Any) -> HybridFrame: ...
    @classmethod
    def from_pandas(
        cls,
        df: pd.DataFrame,
        copy: bool = ...,
        connection: Optional[duckdb.DuckDBPyConnection] = ...,
    ) -> HybridFrame: ...

    def close(self) -> None: ...
    def copy(self) -> HybridFrame: ...

    @property
    def columns(self) -> List[str]: ...
    @property
    def shape(self) -> Tuple[int, int]: ...
    @property
    def dtypes(self) -> pd.Series: ...

    def __getitem__(self, key: Union[str, List[str]]) -> Union[pd.Series, pd.DataFrame]: ...

    def _to_duckdb(self) -> HybridFrame: ...
    def _to_pandas(self, force: bool = ...) -> HybridFrame: ...

    def filter(self, condition: str) -> HybridFrame: ...
    def select(self, columns: Union[str, Sequence[str]]) -> HybridFrame: ...
    def sort_values(self, by: Union[str, List[str]], ascending: bool = ...) -> HybridFrame: ...
    def limit(self, n: int) -> HybridFrame: ...
    def head(self, n: int = ...) -> HybridFrame: ...
    def tail(self, n: int = ...) -> HybridFrame: ...
    def groupby_agg(self, by: Sequence[str], agg_dict: Dict[str, str]) -> HybridFrame: ...
    def join(self, other: HybridFrame, on: Union[str, List[str]], how: str = ...) -> HybridFrame: ...
    def sql(self, query: str) -> HybridFrame: ...
    def show_plan(self) -> str: ...

    def reshape(self, method: str, **kwargs: Any) -> HybridFrame: ...
    def time_series_impute(self, method: str = ..., datetime_col: Optional[str] = ...) -> HybridFrame: ...
    def one_hot_encode(self, columns: Sequence[str], drop_first: bool = ..., dtype: type = ...) -> HybridFrame: ...
    def apply_row_logic(self, func: Callable, **kwargs: Any) -> HybridFrame: ...
    def rename(self, columns: Dict[str, str]) -> HybridFrame: ...
    def drop(self, columns: Union[str, List[str]]) -> HybridFrame: ...
    def fillna(self, value: Any) -> HybridFrame: ...
    def isna(self) -> pd.DataFrame: ...
    def nunique(self) -> pd.Series: ...
    def value_counts(self, column: str) -> pd.Series: ...
    def dropna(self, axis: int = ..., how: str = ..., subset: Optional[Sequence[str]] = ...) -> HybridFrame: ...

    def write_csv(self, path: Union[str, Path], **kwargs: Any) -> None: ...
    def write_parquet(self, path: Union[str, Path], **kwargs: Any) -> None: ...
    def describe(self) -> pd.DataFrame: ...
    def to_pandas(self, force: bool = ..., copy: bool = ...) -> pd.DataFrame: ...
    def to_pandas_iter(self, batch_size: int = ...) -> Iterator[pd.DataFrame]: ...
    def to_ml_ready(self, target_column: str, force: bool = ...) -> Tuple[pd.DataFrame, pd.Series]: ...
    def fetch_chunked(self, batch_size: int = ..., use_arrow: bool = ...) -> Iterator[HybridFrame]: ...
    def to_arrow_reader(self, batch_size: int = ...): ...
    def to_torch_dataloader(self, target_column: str, batch_size: int = ..., shuffle: bool = ..., **kwargs: Any): ...
    def memory_usage(self, deep: bool = ...) -> pd.Series: ...
